### ISSUE TITLE
Super Tactical Droids are indistinguishable in minimal and tournament formats

### ISSUE THREAD

**Issue by derrkater** [Electrynth/legion-hq-web#13]
In both minimal and tournament formats **Super Tactical Droid _Kalani_**, **Super Tactical Droid _Kraken_** and **Super Tactical Droid** are all presented as **Super Tactical Droid**.

**Comment by Electrynth** [comment]
Fixed by 9b61a46 and a57ba09.

**Comment by derrkater** [comment]
Thanks for quick fix! :) Tournament works perfect now but _minimal_ still shows **Super Tactical Droid**.

<img width="1025" alt="Zrzut ekranu 2022-03-28 o 21 13 39" src="https://user-images.githubusercontent.com/32942046/160470076-d3dbf78d-f710-45ec-a68e-b38f2ce0245e.png">
